### ISSUE TITLE
Inconveniente en proceso renovacion automática Codensa

### ISSUE THREAD

**Issue by Econtentsas** [econtent-enter/suscripciones#29]
Hola Cesar,

El día viernes 22 de agosto realicé el proceso de renovación automática de Codensa, veo que en s3 me quedaron creadas las suscripciones en pago ingreso pero no quedo cargada la información en el administrador.  Ej  NIE 12338  tiene pago ingreso del 22 de agosto, y en convenios no está creado el NIE con el identificador de agosto para cobrar.  Qué debo hacer?

**Comment by diemol** [comment]
Se cierra la incidencia dado que se solucionó por medio del correo.
