### ISSUE TITLE
Revisar facturación Codensa solo salieron 3 registros entre 27,28 agost

### ISSUE THREAD

**Issue by Econtentsas** [econtent-enter/suscripciones#30]
Hola Cesar,

Me ayudas por favor a revisar que puede estar fallando en la facturación de Codensa, después de modificar la forma de cobro a los clientes, el día 26 se enviaron 830 registros y entre los días 27 y 28 salieron 3 registros para cargar, en promedio se venían cargando 180 registros.

Te recomiendo para revisar que puede estar fallando, adjunto 3 archivos.
26,27 y 28 agosto. Gracias

![otr_1100_2014082600](https://cloud.githubusercontent.com/assets/6740609/4079753/ad2a906e-2ed8-11e4-90b4-0ff22977eda0.png)
![otr_1100_2014082700](https://cloud.githubusercontent.com/assets/6740609/4079766/c3fec2ba-2ed8-11e4-86d9-fd465f191883.png)
![otr_1100_2014082800](https://cloud.githubusercontent.com/assets/6740609/4079772/d36dd358-2ed8-11e4-9864-7958baf7b59a.png)

**Comment by diemol** [comment]
Se cierra la incidencia ya que fue tratada por correo.
