### ISSUE TITLE
Caso Codensa NIE sin recaudo desde Dic - 2011

### ISSUE THREAD

**Issue by Econtentsas** [econtent-enter/suscripciones#32]
Hola Cesar!!

Este cliente se comunica porque no le volvimos a cobrar en su factura; revisando los cobros el último recaudo que recibimos de este cliente fue en diciembre de 2.011 imagínate solo hasta ahora le estamos facturando de nuevo NIE 1025026, tiene más de 30 identificadores sin cobrar,  que tal tengamos otros más.  Voy hacer una revisión de los clientes Codensa actuales y cruzar contra los envíos no se que pasa.

**Comment by diemol** [comment]
No hay actividad reciente, creo que se solucionó por correo o personalmente, cualquier cosa abrir de nuevo el incidente.
