### ISSUE TITLE
Revisar este caso Codensa

### ISSUE THREAD

**Issue by Econtentsas** [econtent-enter/suscripciones#36]
Hola Cesar!!

Encontre otro caso que nunca le hemos cobrado desde 2.010 NIE 981549 identificador 2040 se envió en 2.010 y el 25907 hasta sept de 2.014.

**Comment by diemol** [comment]
No hay actividad reciente, creo que se solucionó por correo o personalmente, cualquier cosa abrir de nuevo el incidente.
