### ISSUE TITLE
Error al cargar Lis Facturación 004

### ISSUE THREAD

**Issue by Econtentsas** [econtent-enter/suscripciones#44]
Buenos días,

Me está generando un error al cargar el archivo de facturación de condensa que recibí el día de hoy, adjunto el error.  Me preocupa que no sé que sucede y este mes he enviado a facturar muy poquito los OTR que se han enviado son de valores demasiado bajos y los lis 003 no los he podido cargar y el recaudo está muy bajito.  Agradezco revisar este tema.
![error lis facturacion 20 enero](https://cloud.githubusercontent.com/assets/6740609/5818790/6f3cf178-a086-11e4-962f-44f4726df6e0.png)

**Comment by Econtentsas** [comment]
Ok finalmente con lo que tu me dijiste se quito el identificador repetido y se pudieron cargar los Lis003.

**Comment by diemol** [comment]
De acuerdo al último comentario se cierra la incidencia.
