### ISSUE TITLE
Instalar aplicativo s3

### ISSUE THREAD

**Issue by Econtentsas** [econtent-enter/suscripciones#50]
Hola Diego,

Me puedes ayudar por favor a instalar s3 en un equipo de la oficina.

Te agradezco me confirmes la hora.

Saludos,

MFL

**Comment by diemol** [comment]
Hola Mafe,

Lo podríamos hacer el próximo lunes 23.03, a cualquier hora entre 10 y 11 AM.

Saludos,

**Comment by Econtentsas** [comment]
Hola Diego, puede ser mañana 27 de marzo ?  te había respondido que ayer de 8am a 9am que si pero no me dijiste nada.  Me cuentas. gracias,

**Comment by diemol** [comment]
Hola Mafe,

Pues yo pensé que si lo íbamos a hacer el miércoles... En fin, hoy también se puede, pero hoy puedo entre 9am y 10am.

Saludos,

**Comment by diemol** [comment]
El aplicativo fue instalado, cerrando el incidente.
