### ISSUE TITLE
Instalaciòn Aplicaciones

### ISSUE THREAD

**Issue by Econtentsas** [econtent-enter/suscripciones#53]
Hola Diego y Cesar, me pueden colaborar con las instrucciones a seguir para la instalación de suscripciones3, Convenios y el Administrador de S3, en un nuevo equipo de la empresa.
Saludos,

Gracias!!

**Comment by diemol** [comment]
Hola Iván,

Estaba de vacaciones y no había visto el correo.

Usualmente las instalaciones las hacemos por medio de TeamViewer. La podríamos hacer mañana martes o el miércoles entre 1PM y 3PM. Me avisa por fa a que hora le queda mejor.
Si quiere me puede agregar en Skype para que hablemos antes de empezar la instalación. (diego.fernando.molina).

Saludos,

**Comment by Econtentsas** [comment]
Listo Diego, me paree bien el miércoles entre la 1 y las 3.

Saludos,

Ivan


*Iván Bermejo López*
Jefe Circulación

Dirección Cra : 7 74-56 Oficina 704 Bogotá
(571) 3217046 - 310 273 6934
